### ISSUE TITLE
Invalid JSON if tree is called with --prune

### ISSUE THREAD

**Issue by F3nr1s** [nodakai/tree-command#1]
Hi,

My tree version is 1.7 on Arch Linux.
the generated json, if tree is called with the --prune option, is invalid. The reason is, that in every "content" json array, the last element has a commata after it (which indicates another element in the array).
I have created a patch, which fixes the problem on my system.

So long,
Sebastian
[patch.txt](https://github.com/nodakai/tree-command/files/1289951/patch.txt)

**Comment by nodakai** [comment]
Sorry but I'm not the maintainer of this software; I merely cloned it from Debian's Git repo just for convenience.
Could you contact the original author in the readme file?
