### ISSUE TITLE
Link in description is out of date, original repo has moved

### ISSUE THREAD

**Issue by mikaello** [nodakai/tree-command#3]
The original repo seems to be located at https://salsa.debian.org/debian/tree-packaging now.

Message from the frontpage of the service in the description (https://anonscm.debian.org/):
> The alioth.debian.org service is discontinued. Its replacement is a GitLab instance at salsa.debian.org.

Also, a couple of weeks ago version 1.8 was released on [the webpage](http://mama.indstate.edu/users/ice/tree/), but apparently not pushed to a git repo (yet), so that seems worth watching and maybe pull into this mirror if it gets available.

**Comment by nodakai** [comment]
Thanks for the info. Updated accordingly
